src/WebMotors.MVC/Models/Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebMotors.MVC.Models
{
    public class Context : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public Context() : base("name=Context")
        {
        }

        public System.Data.Entity.DbSet<WebMotors.Application.ViewModels.AnuncioViewModel> AnuncioViewModels { get; set; }
    }
}

src/WebMotors.MVC/Controllers/AnunciosController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebMotors.Application.Interfaces;
using WebMotors.Application.ViewModels;

namespace WebMotors.MVC.Controllers
{
    public class AnunciosController : Controller
    {
        private readonly IAnuncioAppService _anuncioAppService;

        public AnunciosController(IAnuncioAppService anuncioAppService)
        {
            _anuncioAppService = anuncioAppService;
        }

        public ActionResult Index()
        {
            return View(_anuncioAppService.GetAll());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnuncioViewModel anuncioViewModel = _anuncioAppService.GetById(id.Value);
            if (anuncioViewModel == null)
            {
                return HttpNotFound();
            }
            return View(anuncioViewModel);
        }

        public async Task<ActionResult> Create()
        {
            var makes = await _anuncioAppService.GetMakes();
            ViewBag.Makes = new SelectList(makes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AnuncioViewModel anuncioViewModel)
        {
            if (ModelState.IsValid)
            {
                var makes = await _anuncioAppService.GetMakes();
                var models = await _anuncioAppService.GetModelsByMake(Convert.ToInt32(anuncioViewModel.Marca));
                var versions = await _anuncioAppService.GetVersionsByModel(Convert.ToInt32(anuncioViewModel.Marca));
                anuncioViewModel.Marca = makes.FirstOrDefault(m => m.Id == Convert.ToInt32(anuncioViewModel.Marca)).Name;
                anuncioViewModel.Modelo = models.FirstOrDefault(m => m.Id == Convert.ToInt32(anuncioViewModel.Modelo)).Name;
                anuncioViewModel.Versao = versions.FirstOrDefault(v => v.Id == Convert.ToInt32(anuncioViewModel.Versao)).Name;
                _anuncioAppService.Add(anuncioViewModel);
                return RedirectToAction("Index");
            }

            return View(anuncioViewModel);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var anuncioViewModel = _anuncioAppService.GetById(id.Value);
            if (anuncioViewModel == null)
            {
                return HttpNotFound();
            }
            var makes = await _anuncioAppService.GetMakes();
            ViewBag.Makes = new SelectList(makes, "Id", "Name");
            return View(anuncioViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AnuncioViewModel anuncioViewModel)
        {
            if (ModelState.IsValid)
            {
                var makes = await _anuncioAppService.GetMakes();
                var models = await _anuncioAppService.GetModelsByMake(Convert.ToInt32(anuncioViewModel.Marca));
                var versions = await _anuncioAppService.GetVersionsByModel(Convert.ToInt32(anuncioViewModel.Marca));
                anuncioViewModel.Marca = makes.FirstOrDefault(m => m.Id == Convert.ToInt32(anuncioViewModel.Marca)).Name;
                anuncioViewModel.Modelo = models.FirstOrDefault(m => m.Id == Convert.ToInt32(anuncioViewModel.Modelo)).Name;
                anuncioViewModel.Versao = versions.FirstOrDefault(v => v.Id == Convert.ToInt32(anuncioViewModel.Versao)).Name;
                _anuncioAppService.Update(anuncioViewModel);
                return RedirectToAction("Index");
            }
            return View(anuncioViewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var anuncioViewModel = _anuncioAppService.GetById(id.Value);
            if (anuncioViewModel == null)
            {
                return HttpNotFound();
            }
            return View(anuncioViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var anuncioViewModel = _anuncioAppService.GetById(id);
            _anuncioAppService.Remove(anuncioViewModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> GetModels(int id)
        {
            var models = await _anuncioAppService.GetModelsByMake(id);
            return Json(models, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> GetVersions(int id)
        {
            var models = await _anuncioAppService.GetVersionsByModel(id);
            return Json(models, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _anuncioAppService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/WebMotors.MVC/Controllers/HomeController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using WebMotors.Application.Interfaces;
using WebMotors.Application.ViewModels;
using WebMotors.Infra.WebMotorsApi.Services;

namespace WebMotors.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAnuncioAppService _anuncioAppService;

        public HomeController(IAnuncioAppService anuncioAppService)
        {
            _anuncioAppService = anuncioAppService;
        }

        public async Task<ActionResult> Index()
        {
            var teste = new WebMotorsApiService();
            var teste11 = await _anuncioAppService.GetMakes();
            var teste1 = await _anuncioAppService.GetModelsByMake(1);
            var teste2 = await _anuncioAppService.GetVehiclesByModel(1);
            var teste3 = await _anuncioAppService.GetVersionsByModel(1);
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/WebMotors.MVC/Views/Anuncios/Create.cshtml
@using WebMotors.Application.ViewModels;
@model AnuncioViewModel

@{
    ViewBag.Title = "Criar Anúncio";
}

<h2>Criar Anúncio</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Marca, (SelectList)ViewBag.Makes, new { @class = "form-control", onchange = "getModels(); getVersions()" })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Modelo, new SelectList(new List<ModelViewModel>(), "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Versao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Versao, new SelectList(new List<VersionViewModel>(), "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Versao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quilometragem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quilometragem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quilometragem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Observacao, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function () {
            getModels();
            getVersions();
        });

        function getModels() {
            var makeId = $("#Marca").val();
            $.get(`/Anuncios/GetModels/${makeId}`, function (data) {
                $('#Modelo').children().remove();
                $('#Modelo').attr('disabled', 'true');
                data.forEach(function (item, index) {
                    $('#Modelo').append(`<option value="${item.Id}">${item.Name}</option>`);
                })
                $('#Modelo').attr('disabled', false);
            });
        }

        function getVersions() {
            var makeId = $("#Marca").val();
            $.get(`/Anuncios/GetVersions/${makeId}`, function (data) {
                $('#Versao').children().remove();
                $('#Versao').attr('disabled', 'true');
                data.forEach(function (item, index) {
                    $('#Versao').append(`<option value="${item.Id}">${item.Name}</option>`);
                })
                $('#Versao').attr('disabled', false);
            });
        }
    </script>
}

src/WebMotors.MVC/Views/Anuncios/Delete.cshtml
@model WebMotors.Application.ViewModels.AnuncioViewModel

@{
    ViewBag.Title = "Remover Anúncio";
}

<h2>Remover Anúncio</h2>

<h3>Você tem certeza que deseja remover esse anúncio?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Versao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Versao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quilometragem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quilometragem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Lista", "Index")
        </div>
    }
</div>

src/WebMotors.MVC/Views/Anuncios/Details.cshtml
@model WebMotors.Application.ViewModels.AnuncioViewModel

@{
    ViewBag.Title = "Detalhes do Anúncio";
}

<h2>Detalhes do Anúncio</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Versao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Versao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quilometragem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quilometragem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Lista", "Index")
</p>

src/WebMotors.MVC/Views/Anuncios/Edit.cshtml
@using WebMotors.Application.ViewModels
@model AnuncioViewModel

@{
    ViewBag.Title = "Editar Anúncio";
}

<h2>Editar Anúncio</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Marca, (SelectList)ViewBag.Makes, new { @class = "form-control", onchange = "getModels(); getVersions()" })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Modelo, new SelectList(new List<ModelViewModel>(), "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Versao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Versao, new SelectList(new List<VersionViewModel>(), "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Versao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quilometragem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quilometragem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quilometragem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function () {
            selectItem(document.getElementById('Marca'), '@(Model.Marca)');
            getModels();
            getVersions();            
            selectItem(document.getElementById('Modelo'), '@(Model.Modelo)');
            selectItem(document.getElementById('Versao'), '@(Model.Versao)');            
        });

        function getModels() {
            var makeId = $("#Marca").val();
            $.get(`/Anuncios/GetModels/${makeId}`, function (data) {
                $('#Modelo').children().remove();
                $('#Modelo').attr('disabled', 'true');
                data.forEach(function (item, index) {
                    $('#Modelo').append(`<option value="${item.Id}">${item.Name}</option>`);
                })
                $('#Modelo').attr('disabled', false);
            });
        }

        function getVersions() {
            var makeId = $("#Marca").val();
            $.get(`/Anuncios/GetVersions/${makeId}`, function (data) {
                $('#Versao').children().remove();
                $('#Versao').attr('disabled', 'true');
                data.forEach(function (item, index) {
                    $('#Versao').append(`<option value="${item.Id}">${item.Name}</option>`);
                })
                $('#Versao').attr('disabled', false);
            });
        }

        function selectItem(element, value) {
            for (var i = 0; i < element.options.length; i++) {
                if (element.options[i].text === value) {
                    element.selectedIndex = i;
                    break;
                }
            }
        }
    </script>
}

src/WebMotors.MVC/Views/Anuncios/Index.cshtml
@model IEnumerable<WebMotors.Application.ViewModels.AnuncioViewModel>

@{
    ViewBag.Title = "Anúncios";
}

<h2>Anúncios</h2>

<p>
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Versao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ano)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quilometragem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Observacao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Versao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ano)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quilometragem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Observacao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.Id }) |
            @Html.ActionLink("Remover", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

src/WebMotors.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/WebMotors.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebMotors", "Index", "Anuncios", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anuncios", "Index", "Anuncios")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WebMotors</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>